### ISSUE TITLE
Add Https to URl Endpoint

### ISSUE THREAD

**Issue by Olatokumbo** [alademerin/gr8fit-weather-app#1]
Hey bro, it was nice talking to you earlier. @alademerin 
Hopefully adding `https` should fix the site.
Regards 

<img width="615" alt="Screenshot 2023-06-08 at 1 32 14 pm" src="https://github.com/alademerin/gr8fit-weather-app/assets/30363095/7f3e6e65-f280-4a37-bf12-50cad34cbf8b">

**Comment by alademerin** [comment]
Hey Bro, it was really nice talking to you earlier as well @Olatokumbo 

Thanks for lending me your sharp eyes on this one. I must've gotten carried away while developing that I just copied the base URL from their website without reading that it could be either HTTP or HTTPS haha.

![image](https://github.com/alademerin/gr8fit-weather-app/assets/106078989/c1bc7cbb-d0f6-4a28-ab6c-a0e098f6430e)


it works now! thanks 😁
